name: build

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "游戏的包名: com.fengchi.ldjx.nearme.gamecenter"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          cache: gradle

      - name: Build module
        run: |
          chmod +x ./gradlew
          sed -i 's/moduleDescription = "/moduleDescription = "(${{ github.event.inputs.package_name }}) /g' module.gradle
          sed -i "s/com.game.packagename/${{ github.event.inputs.package_name }}/g" module/src/main/cpp/game.h
          ./gradlew :module:assembleRelease

      - name: Upload release artifact
        uses: actions/upload-artifact@v3
        with:
          name: zygisk-il2cppdumper
          path: out/magisk_module_release/
